name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      PACKAGES_OUTPUT_DIR: ${{ github.workspace }}/artifacts/packages
    
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Get version tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Check tag
        run: |
          echo ${{ steps.extract_tag.outputs.tag }}

      - name: Pack UaDetector
        run: |
          dotnet pack src/UaDetector \
            --configuration Release \
            --output "$PACKAGES_OUTPUT_DIR" \
            -p:PackageVersion=${{ steps.extract_tag.outputs.tag }}
          
      - name: Add local NuGet feed
        run: dotnet nuget add source "$PACKAGES_OUTPUT_DIR" --name local

      - name: Pack UaDetector.MemoryCache
        run: |
          dotnet pack src/UaDetector.MemoryCache \
            --configuration Release \
            --output "$PACKAGES_OUTPUT_DIR" \
            -p:PackageVersion=${{ steps.extract_tag.outputs.tag }}
